import android.support.v4.widget.DrawerLayout;
import android.support.v4.app.*;
import android.app.*;
import android.view.*;
import android.widget.*;
import android.content.*;
import android.text.*;
import android.webkit.*;
//import android.support.v7.app.*;
import android.support.v7.widget.*;
import processing.event.TouchEvent.*;
import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.graphics.*;
import android.graphics.drawable.*;
import android.util.*;
import android.text.style.*;
import android.text.TextWatcher;
import android.view.inputmethod.*;
import android.os.Environment;
import android.content.res.AssetManager;
import android.text.method.*;
import java.io.*;
import org.apache.commons.io.FileUtils;
import org.xmlpull.v1.*;
void draw(){
  
}
